declare module "*.jpg";
declare module "*.JPG";
declare module "*.jpeg";
declare module "*.JPEG";
declare module "*.png";
declare module "*.PNG";
declare module "*.gif";
declare module "*.webp";
declare module "*.svg";